services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"     # Web UI
      - "50000:50000"   # Agentes JNLP
    environment:
      - JENKINS_OPTS=--prefix=/
    volumes:
      - jenkins_home:/var/jenkins_home
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/login > /dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 90s

  ngrok:
    build:
      context: ./ngrok
      dockerfile: Dockerfile
    container_name: ngrok
    depends_on:
      jenkins:
        condition: service_healthy
    env_file: .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      [
        "start",
        "--all",
        "--config", "/etc/ngrok.yml",
        "--authtoken", "${NGROK_AUTHTOKEN}",
        "--log", "stdout",
        "--log-level", "debug",
        "--log-format", "logfmt"
      ]
    ports:
      - "4040:4040"   # panel/API de ngrok
    restart: unless-stopped

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"   # UI SonarQube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/api/system/status | grep -q 'UP' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s


volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
